# name: NestJS CI/CD

# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]

# jobs:
#   build-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Lint code
#         run: npm run lint

#       - name: Run tests
#         run: npm run test

#       - name: Build project
#         run: npm run build

#   deploy:
#     needs: build-test
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install --production

#       - name: Build project
#         run: npm run build

#       - name: Deploy via SSH
#         uses: appleboy/ssh-action@v0.1.9
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_KEY }}
#           port: 22
#           script: |
#             cd /path/to/project
#             git pull
#             npm install --production
#             npm run build
#             pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app
